name: Deploy to Timeweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TIMEWEB_SSH_KEY }}

      - name: Deploy via SSH
        run: ssh -o StrictHostKeyChecking=no root@95.140.153.181 "bash /root/deploy.sh"
