name: Deploy to Timeweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.TIMEWEB_SSH_KEY }}

    - name: Deploy to server
      run: ssh -o StrictHostKeyChecking=no root@95.140.153.181 "bash /root/deploy.sh"
